sudo: required
language: python
env:
  secure: PAsZwS8foVUSteR87Zjsi97TLfNOWvJA6sWdPt9+1pnEmEuJRt4qwPu4jmpMx+0BdH6wbPbNwhmZUV/iNsjp0OffY+EZTyr+giV/OxaOT8ZdKWjingLdk+Gwz3fobE1JhqsN58eWxZA5vab3hUXou1Sz+8SQXVov2dMRx0MC3ls=
python:
- '2.6'
- '3.5'
before_install:
- ifconfig -a
- sudo /sbin/modprobe tun
- sudo apt-get update -qq
- sudo apt-get install -qq dynamips
- wget -q $IOS_URL
install:
- ls -l
- pip install .
- ifconfig -a
- dynamips -s 0:0:tap:tap0 -P 3725 -T 2001 --idle-pc=0x607081e0 -C r1.txt c3725-advsecurityk9-mz.124-25c.bin &
- sleep 60
- sudo ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
- ping -c 4 1.1.1.2
script: py.test
branches:
  only:
  - tests
