language: python
python:
  - "2.6"
  - "3.5"
# Deps
before_install:
	- ifconfig -a
addons:
  apt:
    packages:
    - dynamips
install:
  - pip install .
  - dynamips
# command to run tests
script: py.test
# Restrict to Test branch
branches:
  only:
      - tests