sudo: required

language: python
python:
  - "2.6"
  - "3.5"
# Deps
before_install:
  - ifconfig -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq dynamips
install:
  - pip install .
  - sudo ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
  - ifconfig -a
# command to run tests
script: py.test
# Restrict to Test branch
branches:
  only:
      - tests
