name: Webhook

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
      resumeUrl:
        description: 'n8n thing'
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "MSG[1] --  ${{ inputs.message }}"
          echo "MSG[2] --  ${{ inputs.resumeUrl }}"